<script lang="ts">
  import { onMount } from "svelte";
  import { command, native, type Runtime } from "./runtime";
  type Alias = {id:string;revision:string;phrase:string};
  let { runtime,panel,aliases }:{runtime:Runtime|null;panel:string|null;aliases:Alias[]}=$props();
  type Scope={id:string;revision:string;alias:string;alias_revision:string;name:string;excluded:boolean};
  type Candidate={id:string;revision:string;name:string;scope:Scope;source:"observed_transition";transitions:number};
  type Active={id:string;qualified:boolean;transitions:number;finishing:boolean};
  type Progress={active:Active|null;last:string|null};
  type View=Progress&{snapshot:{scopes:Scope[];candidates:{candidate:Candidate;validated:boolean}[]}};
  let view=$state<View|null>(null);let progress=$state<Progress|null>(null);let alias=$state("");let scope=$state("");let name=$state("");let editing=$state<Candidate|null>(null);let busy=$state(false);let stopping=$state(false);let error=$state("");let mounted=false;let generation=0;let context="";let polling=false;
  const enabled=$derived(native&&!!panel&&runtime?.connected&&!runtime.locked);
  $effect(()=>{const next=`${panel}:${runtime?.action_epoch}:${runtime?.connected}:${runtime?.locked}`;if(next!==context){context=next;generation++;view=null;progress=null;editing=null;}});
  async function run(work:()=>Promise<void>){if(!enabled||busy)return;busy=true;error="";try{await work();}catch(e){if(mounted)error=String(e);}finally{busy=false;}}
  async function refresh(){const expected=++generation;const value=await command<View>("teaching_status",{panel});if(mounted&&expected===generation){view=value;progress=value;}}
  async function roster(excluded:boolean){await run(async()=>{const selected=aliases.find(a=>a.id===alias);if(!selected)return;await command("set_teaching_scope",{panel,alias:selected.id,revision:selected.revision,scope:null,excluded});await refresh();});}
  async function exclude(item:Scope){await run(async()=>{await command("set_teaching_scope",{panel,alias:null,scope:item.id,revision:item.revision,excluded:true});await refresh();});}
  async function start(){await run(async()=>{const selected=view?.snapshot.scopes.find(s=>s.id===scope&&!s.excluded);if(!selected||!name.trim())return;await command("start_demonstration",{panel,scope:selected.id,revision:selected.revision,name});await refresh();});}
  async function stop(save:boolean){const active=progress?.active;if(!panel||!active||stopping)return;stopping=true;const expected=generation;try{await command("stop_demonstration",{panel,id:active.id,save});}catch(e){if(mounted&&expected===generation)error=String(e);}finally{stopping=false;}}
  async function change(candidate:Candidate,newName:string|null){await run(async()=>{await command("change_demonstration",{panel,id:candidate.id,revision:candidate.revision,name:newName});editing=null;await refresh();});}
  onMount(()=>{mounted=true;const timer=setInterval(()=>{if(!enabled||polling||busy)return;polling=true;const expected=generation;void command<Progress>("teaching_progress",{panel}).then(value=>{if(mounted&&expected===generation){const finished=progress?.active&&!value.active;progress=value;if(finished)void run(refresh);}}).catch(()=>{}).finally(()=>polling=false);},1000);return()=>{mounted=false;generation++;clearInterval(timer);if(panel&&progress?.active)void command("stop_demonstration",{panel,id:progress.active.id,save:false}).catch(()=>{});};});
</script>
<section class="section">
 <div class="flex items-center justify-between"><span class="av-kicker">Teach an app-opening routine</span><button class="av-btn av-btn-ghost av-btn-sm" disabled={!enabled||busy} onclick={()=>run(refresh)}>Refresh teaching</button></div>
 <p class="av-hint">Choose one saved app and allow observation with the Windows verification above. This watches only whether that exact app opens and comes forward. It records no titles, screen images or typed text.</p>
 <label class="av-label" for="teach-alias">Observation scope</label><select id="teach-alias" class="av-select" bind:value={alias} disabled={!enabled||busy}><option value="">Choose a saved app</option>{#each aliases as app}<option value={app.id}>{app.phrase}</option>{/each}</select>
 <div class="flex gap-2"><button class="av-btn av-btn-secondary" disabled={!enabled||busy||!alias} onclick={()=>roster(false)}>Allow selected app</button><button class="av-btn av-btn-ghost" disabled={!enabled||busy||!alias} onclick={()=>roster(true)}>Exclude selected app</button></div>
 {#each view?.snapshot.scopes??[] as item}<p class="av-hint">{item.name}: {item.excluded?"excluded":"allowed for explicit teaching"} {#if !item.excluded}<button class="av-btn av-btn-ghost av-btn-sm" disabled={!enabled||busy} onclick={()=>exclude(item)}>Exclude</button>{/if}</p>{/each}
 <label class="av-label" for="teach-scope">App to demonstrate</label><select id="teach-scope" class="av-select" bind:value={scope} disabled={!enabled||busy||!!progress?.active}><option value="">Choose an allowed app</option>{#each view?.snapshot.scopes.filter(s=>!s.excluded)??[] as item}<option value={item.id}>{item.name}</option>{/each}</select>
 <label class="av-label" for="teach-name">Routine name</label><input id="teach-name" class="av-input" bind:value={name} maxlength="128" disabled={!enabled||busy||!!progress?.active}/>
 {#if progress?.active}<div role="status"><h3>{progress.active.finishing?"Finishing observation…":"Watching selected app"}</h3><p class="av-hint">{progress.active.qualified?"A matching app-opening transition was observed. Stop to save the candidate.":"Start with the app closed, then open it yourself. Nothing will be closed for you."} {progress.active.transitions} changed states. Stops after five minutes; other accepted work takes priority.</p><div class="flex gap-2"><button class="av-btn av-btn-secondary" disabled={stopping||!enabled||progress.active.finishing} onclick={()=>stop(true)}>Stop and save candidate</button><button class="av-btn av-btn-ghost" disabled={stopping} onclick={()=>stop(false)}>Cancel</button></div></div>{:else}<button class="av-btn av-btn-secondary" disabled={!enabled||busy||!scope||!name.trim()} onclick={start}>Start watching</button>{/if}
 {#if progress?.last}<p class="av-hint" role="status">{progress.last}</p>{/if}
 {#each view?.snapshot.candidates??[] as item}<div class="row"><div><h3>{item.candidate.name}</h3><p class="av-hint">{item.candidate.scope.name} · observed app transition{item.validated?" · past verified invocation":" · candidate, not yet validated"}. We did not record which click opened it. {#if view?.snapshot.scopes.some(s=>s.id===item.candidate.scope.id&&s.revision===item.candidate.scope.revision&&!s.excluded)}Say “Run routine {item.candidate.name}”; current app permission is required.{:else}Observation scope changed or was excluded; demonstrate again before running.{/if}</p></div><div class="flex gap-2"><button class="av-btn av-btn-ghost" disabled={busy||!enabled} onclick={()=>{editing=item.candidate;name=item.candidate.name;}}>Rename</button><button class="av-btn av-btn-ghost" disabled={busy||!enabled} onclick={()=>change(item.candidate,null)}>Delete candidate</button></div></div>{/each}
 {#if editing}<p class="av-hint">Rename “{editing.name}” using the routine name above. This creates an unvalidated revision.</p><button class="av-btn av-btn-secondary" disabled={busy||!name.trim()} onclick={()=>{if(editing)void change(editing,name);}}>Save correction</button>{/if}
 {#if error}<p class="av-hint text-amber-200" role="status">{error}</p>{/if}
</section>
